module.exports = {
  men: [
    { name_ar: "قص شعر", icon: "fa-cut", service_type: "main" },
    { name_ar: "حلاقة شعر ولحية", icon: "fa-scissors", service_type: "main" },
    { name_ar: "تشذيب لحية", icon: "fa-user-tie", service_type: "main" },
    { name_ar: "سشوار رجال", icon: "fa-wind", service_type: "main" },
    { name_ar: "صبغة شعر رجال", icon: "fa-palette", service_type: "main" },
    { name_ar: "فرد شعر رجال", icon: "fa-align-justify", service_type: "main" },
    { name_ar: "بروتين/كيراتين شعر", icon: "fa-magic", service_type: "main" },
    { name_ar: "قص أطفال", icon: "fa-child", service_type: "main" },
    { name_ar: "تنظيف بشرة رجال", icon: "fa-mask", service_type: "main" },
    { name_ar: "حواجب رجال", icon: "fa-eye", service_type: "main" },
    { name_ar: "واكس الوجه", icon: "fa-th-large", service_type: "main" },
    { name_ar: "حمام زيت", icon: "fa-tint", service_type: "main" },
    { name_ar: "مساج رأس", icon: "fa-head-side", service_type: "main" },

    { name_ar: "بودرة/سبراي تثبيت", icon: "fa-spray-can", service_type: "add_on" },
    { name_ar: "سيروم شعر", icon: "fa-flask", service_type: "add_on" },
    { name_ar: "كريم معالج", icon: "fa-vial", service_type: "add_on" },
    { name_ar: "منشفة ساخنة", icon: "fa-hot-tub", service_type: "add_on" },
    { name_ar: "ماسك مرطب", icon: "fa-tint", service_type: "add_on" },
    { name_ar: "ماسك مقشر", icon: "fa-leaf", service_type: "add_on" },
    { name_ar: "ماسك مغذي", icon: "fa-seedling", service_type: "add_on" },
    { name_ar: "معطر شعر", icon: "fa-burn", service_type: "add_on" },
    { name_ar: "حلاقة بالخيط", icon: "fa-thread", service_type: "add_on" }
  ],
  women: [
    { name_ar: "قص شعر نسائي", icon: "fa-cut", service_type: "main" },
    { name_ar: "سشوار وتصفيف", icon: "fa-wind", service_type: "main" },
    { name_ar: "صبغة كاملة", icon: "fa-palette", service_type: "main" },
    { name_ar: "هايلايت/بالياج", icon: "fa-brush", service_type: "main" },
    { name_ar: "كيراتين/بوتوكس الشعر", icon: "fa-magic", service_type: "main" },
    { name_ar: "فرد الشعر", icon: "fa-align-justify", service_type: "main" },
    { name_ar: "حمام زيت", icon: "fa-tint", service_type: "main" },
    { name_ar: "إضافة وصلات شعر", icon: "fa-ribbon", service_type: "main" },
    { name_ar: "تنظيف بشرة عميق", icon: "fa-mask", service_type: "main" },
    { name_ar: "بدكير ومنكير", icon: "fa-hand-sparkles", service_type: "main" },
    { name_ar: "تركيب أظافر جل", icon: "fa-fingerprint", service_type: "main" },
    { name_ar: "تنظيف/تشكيل حواجب", icon: "fa-eye", service_type: "main" },
    { name_ar: "مكياج كامل", icon: "fa-paint-brush", service_type: "main" },
    { name_ar: "مكياج خفيف", icon: "fa-brush", service_type: "main" },
    { name_ar: "تسريحة مناسبات", icon: "fa-crown", service_type: "main" },
    { name_ar: "تسريحة يومية", icon: "fa-star", service_type: "main" },
    { name_ar: "علاج قشرة الشعر", icon: "fa-bong", service_type: "main" },
    { name_ar: "صبغة حواجب", icon: "fa-eye-dropper", service_type: "main" },
    { name_ar: "صبغة رموش", icon: "fa-eye", service_type: "main" },
    { name_ar: "حمام مغربي", icon: "fa-spa", service_type: "main" },
    { name_ar: "ميكروبليدينغ حواجب", icon: "fa-pen", service_type: "main" },

    { name_ar: "ماسك مرطب", icon: "fa-tint", service_type: "add_on" },
    { name_ar: "ماسك مقشر", icon: "fa-leaf", service_type: "add_on" },
    { name_ar: "ماسك مغذي", icon: "fa-seedling", service_type: "add_on" },
    { name_ar: "سيروم شعر", icon: "fa-flask", service_type: "add_on" },
    { name_ar: "سبراي تثبيت", icon: "fa-spray-can", service_type: "add_on" },
    { name_ar: "ترطيب شفاه", icon: "fa-grin-beam", service_type: "add_on" },
    { name_ar: "رموش فردية", icon: "fa-eye", service_type: "add_on" },
  ]
};